services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: security-users
    ports:
      - "4001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_MENU_API_URL: "/api/Menu"
      NEXT_PUBLIC_PERMISOS_API_URL: "/api/Permisos"
