services:
  as400-api:
    build: .
    container_name: as400_api
    env_file: .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
