// src/components/dashboard/iconMap.ts
import {
  Users,
  Package,
  Truck,
  FileText,
  List,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UserCircle,
  UserSquare,
  UserCog,
  Shield,
  ShieldCheck,
  ShieldX,
  ShieldUser,
  LayoutGrid,
  Lock,
  Unlock,
  Key,
  Settings,
  Cog,
  Home,
  Building,
  Briefcase,
  Calendar,
  CalendarCheck,
  CalendarX,
  Clock,
  AlarmClock,
  Bell,
  BellOff,
  Mail,
  MailOpen,
  Inbox,
  Send,
  MessageCircle,
  MessageSquare,
  Phone,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,
  Server,
  Database,
  Globe,
  Map,
  MapPin,
  Compass,
  Search,
  Eye,
  EyeOff,
  Camera,
  Image,
  Video,
  Music,
  Mic,
  MicOff,
  Volume,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Rewind,
  FastForward,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Plus,
  Minus,
  X,
  Check,
  Edit,
  Trash,
  Save,
  Download,
  Upload,
  Cloud,
  CloudDownload,
  CloudUpload,
  Folder,
  FolderOpen,
  File,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  Tag,
  Tags,
  Bookmark,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  AlertTriangle,
  AlertCircle,
  Info,
  HelpCircle,
  Sun,
  Moon,
  Zap,
  Flame,
  Gift,
  ShoppingCart,
  CreditCard,
  DollarSign,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  Activity,
  Award,
  Trophy,
  Flag,
  Anchor,
} from "lucide-react";

export const iconMap = {
  users: Users,
  user: User,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userCheck: UserCheck,
  userX: UserX,
  userCircle: UserCircle,
  userSquare: UserSquare,
  userCog: UserCog,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shieldX: ShieldX,
  shieldUser: ShieldUser,
  layoutGrid: LayoutGrid,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  settings: Settings,
  cog: Cog,
  home: Home,
  building: Building,
  briefcase: Briefcase,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  calendarX: CalendarX,
  clock: Clock,
  alarmClock: AlarmClock,
  bell: Bell,
  bellOff: BellOff,
  mail: Mail,
  mailOpen: MailOpen,
  inbox: Inbox,
  send: Send,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  phone: Phone,
  smartphone: Smartphone,
  tablet: Tablet,
  monitor: Monitor,
  laptop: Laptop,
  server: Server,
  database: Database,
  globe: Globe,
  map: Map,
  mapPin: MapPin,
  compass: Compass,
  search: Search,
  eye: Eye,
  eyeOff: EyeOff,
  camera: Camera,
  image: Image,
  video: Video,
  music: Music,
  mic: Mic,
  micOff: MicOff,
  volume: Volume,
  volume2: Volume2,
  volumeX: VolumeX,
  play: Play,
  pause: Pause,
  skipForward: SkipForward,
  skipBack: SkipBack,
  rewind: Rewind,
  fastForward: FastForward,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  edit: Edit,
  trash: Trash,
  save: Save,
  download: Download,
  upload: Upload,
  cloud: Cloud,
  cloudDownload: CloudDownload,
  cloudUpload: CloudUpload,
  folder: Folder,
  folderOpen: FolderOpen,
  file: File,
  filePlus: FilePlus,
  fileMinus: FileMinus,
  fileCheck: FileCheck,
  fileX: FileX,
  tag: Tag,
  tags: Tags,
  bookmark: Bookmark,
  star: Star,
  heart: Heart,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  smile: Smile,
  frown: Frown,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  info: Info,
  helpCircle: HelpCircle,
  sun: Sun,
  moon: Moon,
  zap: Zap,
  flame: Flame,
  gift: Gift,
  shoppingCart: ShoppingCart,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  barChart: BarChart,
  pieChart: PieChart,
  activity: Activity,
  award: Award,
  trophy: Trophy,
  flag: Flag,
  anchor: Anchor,
  package: Package,
  truck: Truck,
  "file-text": FileText,
  list: List,
};
